name: Build GluGlu Browser

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build for Windows
        run: go build -o gluglu.exe ./cmd/gluglu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gluglu-windows
          path: gluglu.exe